name: cron

on:

  workflow_dispatch:

  schedule:

    - cron: "* */24 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  cron:

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
      
        with:
          python-version: '3.11'
          check-latest: true
      - run: python service.py